source 'https://rubygems.org'

gem 'jekyll',      '= 2.5.3'
gem 'asciidoctor', '= 1.5.2'

# gem 'coderay', '= 1.1.0'
gem 'pygments.rb', '= 0.6.3'

group :jekyll_plugins do
  gem 'jekyll-asciidoc', '= 1.0.0'
end
